# Generated by Django 2.1 on 2019-09-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='iso',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.RemoveField(
            model_name='states',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='iso',
            name='iso',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='states',
            name='states',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
