# Generated by Django 2.1 on 2019-09-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20190927_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='iso',
            old_name='iso',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='states',
            old_name='states',
            new_name='name',
        ),
        migrations.AddField(
            model_name='site',
            name='area_hectares',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='justification',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
